version: '3'

services:
  apache:
    build: ./docker/build/apache
    links:
      - mysql
    ports:
      - "8089:80"
    volumes:
      - ./docker/etc/apache/drupal.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ./docker/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/etc/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
      - ./log/apache/drupal:/var/log/apache2

      # drupal root
      #- ./app/drupal/build:/var/web/app/drupal/build
      #- ./app/drupal/config:/var/web/app/drupal/config
      #- ./app/drupal/drush:/var/web/app/drupal/drush
      #- ./app/drupal/scripts:/var/web/app/drupal/scripts
      # drupal web dir
      #- ./app/drupal/web/modules:/var/web/app/drupal/web/modules
      #- ./app/drupal/web/themes:/var/web/app/drupal/web/themes
      #- ./app/drupal/web/profiles:/var/web/app/drupal/web/profiles
      #- ./app/drupal/web/sites:/var/web/app/drupal/web/sites
      # drupal web files
      #- ./app/drupal/composer.json:/var/web/app/drupal/composer.json
      #- ./app/drupal/composer.lock:/var/web/app/drupal/composer.lock
      #- ./app/drupal/web/index.php:/var/web/app/drupal/web/index.php
      #- ./app/drupal/web/autoload.php:/var/web/app/drupal/web/autoload.php
      #- ./app/drupal/load.environment.php:/var/web/app/drupal/load.environment.php
      #- ./app/drupal/web/update.php:/var/web/app/drupal/web/update.php
      #- ./app/drupal/web/robots.txt:/var/web/app/drupal/web/robots.txt
      #- ./app/drupal/web/.htaccess:/var/web/app/drupal/web/.htaccess
      #*/

      - ./app/drupal:/var/web/app/drupal:cached
      # drupal vendor
      - drupal-vendor:/var/web/app/drupal/vendor:delegated

      - ./app/drupal/web/sites/default/files/archive:/var/web/app/drupal/web/sites/default/files/archive
      ## exclude
      - /var/web/app/drupal/web/sites/default/files
      # drupal media files
      - drupal-files:/var/web/drupal/web/sites/default/files:delegated

  mysql:
    build:
        context: ./docker/build/mysql
        dockerfile : Dockerfile
        args:
            MYSQL_ROOT_PASSWORD: toto44
    ports:
      - "3315:3306"
    volumes:
      - ./docker/etc/mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - /var/lib/mysql/
      - ./data:/data
    environment:
      MYSQL_ROOT_PASSWORD: toto44
      MYSQL_DATABASE: drupal_test
#    
#  phpmyadmin:
#    image: nazarpc/phpmyadmin
#    links:
#      - mysql
#    ports:
#      - "8002:80"

volumes:
  drupal-vendor:
  drupal-files: