<?php

/**
 * @file
 * Contains us2e_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function us2e_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the us2e_core module.
    case 'help.page.us2e_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function us2e_core_theme() {
  return [
    'us2e_core' => [
      'render element' => 'children',
    ],
  ];
}
